### ISSUE TITLE
[Enhancement] Ability to dump to a specific struct format (fixed byte size)

### ISSUE THREAD

**Issue by ProjectRevoTPP** [TwitchPlaysPokemon/pret3#1]
self-explanatory

**Comment by ProjectRevoTPP** [comment]
it would be good if i had a byte dump to specified array program
like, if i gave it
.2byte, .string(11), .string(8), .byte, .2byte, .4byte, .2byte, .2byte(6), .4byte(5)
for strings the num is the padding so
.string "POOCHY$", 11 @nickname
for byte 2byte and 4byte its the number of them in the sequence
.4byte 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0xFFFF0000 @unknown, padding and memory allocation?
more specifically:
.2byte, .string(11), .string(8), .byte, .2byte, .4byte, .2byte, .2byte(6), .4byte(5)
then i input:

1E 01 CA C9 C9 BD C2 D3 FF 00 00 00 00 C4 C3 C7 C7 D3 FF 00 00 07 00 00 FF 0F 00 0C 44 00 2E 00 2C 00 24 00 50 01 0A 04 0A 03 04 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF 00 00

.2byte 0x011E @pokemon
.string "POOCHY$", 11 @nickname
.string "JIMMY$", 8 @name
.byte 0x07 @trainer sprite
.2byte 0x0000 @padding
.4byte 0x0C000FFF @unknown, bitflags?
.2byte 0x0044 @rank
.2byte 0x002E, 0x002C, 0x0024, 0x0150 @moves
.byte 0x0A, 0x04, 0x0A, 0x03, 0x04, 0x32
.4byte 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0xFFFF0000 @unknown, padding and memory allocation?

for future unknown data structs that we document
then we can just auto dump it all

**Comment by aaaaaa123456789** [comment]
You can now do this with a script.

```
: species ID
$species :2 int:2
.2byte $species @pokemon
: get the nickname
$data :11
$length $data bytesuntil:0xff add:1
$nickname $data text:$length
.string "$nickname", 11 @nickname
: get the name
$data :8
$length $data bytesuntil:0xff add:1
$name $data text:$length
.string "$name", 8 @name
: rest of the stuff
$sprite :1 int:1
.byte $sprite @sprite
$padding :2 int:2
.2byte $padding @padding
$bitflags :4 int:4
.4byte $bitflags @unknown, bitflags?
$rank :2 int:2
.2byte $rank @rank
$moves :8 multi16:4
.2byte $moves @moves
$unknown :6 multi8:6
.byte $unknown
$padding :20 multi32:5
.4byte $padding @unknown, padding and memory allocation?
```
